plugins {
    id 'com.android.application'
}

android {
    namespace 'com.yamil.usagebubble'
    compileSdk 35

    defaultConfig {
        applicationId 'com.yamil.usagebubble'
        minSdk 26
        targetSdk 35
        versionCode 3
        versionName '1.0'
    }

    signingConfigs {
        debugStable {
            storeFile file('usagebubble-debug.keystore')
            storePassword 'usagebubble'
            keyAlias 'usagebubble'
            keyPassword 'usagebubble'
        }
    }

    buildTypes {
        debug {
            signingConfig signingConfigs.debugStable
        }
    }
}
